In [96]:
import numpy as np

In [97]:
inputs=np.array([
 [1,2],
 [3,4],
 [5,6]
],dtype=float)
targets=np.array([
    [7],
    [8],
    [9]
],dtype=float)

In [98]:
## normalize data
inputs = inputs / np.max(inputs, axis=0)
targets = targets / 100.0

In [99]:
print(inputs)
print(targets)

[[0.2        0.33333333]
 [0.6        0.66666667]
 [1.         1.        ]]
[[0.07]
 [0.08]
 [0.09]]


In [100]:
def activate(x):## sigmoid
    return 1/(1+np.exp(-x))
def activate_derivative(x):
    return x*(1-x)

In [101]:
## example for transpose
print(input.T)

[[1. 3. 5.]
 [2. 4. 6.]]


In [102]:
num_input_features = inputs.shape[1]   # 2
num_hidden_neurons = 3
num_outputs = targets.shape[1]  

In [103]:
epoch=1000
training_factor=0.2 ## eta

In [104]:
## input to hidden
weights_input_to_hidden = np.random.uniform(size=(num_input_features, num_hidden_neurons))
bias_hidden = np.random.uniform(size=(1, num_hidden_neurons))

In [105]:
print(weights_input_to_hidden)
print(bias_hidden)

[[0.94835184 0.69186649 0.52582715]
 [0.91589253 0.3718654  0.97597152]]
[[0.75208351 0.97360204 0.39395106]]


In [106]:
weights_hidden_to_output=np.random.uniform(size=(num_hidden_neurons,num_outputs))
bias_output=np.random.uniform(size=(1,num_outputs))

In [107]:
print(weights_hidden_to_output)
print(bias_output)

[[0.48601183]
 [0.36819488]
 [0.3591712 ]]
[[0.08556209]]


In [108]:
for _ in range(epoch):
     # ---- Forward pass ----
    hidden_input = np.dot(inputs, weights_input_to_hidden) + bias_hidden
    hidden_output = activate(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_to_output) + bias_output
    predicted_output = activate(final_input)

    # ---- Calculate error ----
    output_error = targets - predicted_output

    # ---- Backpropagation ----
    output_gradient = output_error * activate_derivative(predicted_output)

    hidden_error = np.dot(output_gradient, weights_hidden_to_output.T)
    hidden_gradient = hidden_error * activate_derivative(hidden_output)

    # ---- Update weights ----
    weights_hidden_to_output += np.dot(hidden_output.T, output_gradient) * training_factor
    weights_input_to_hidden += np.dot(inputs.T, hidden_gradient) * training_factor

    # ---- Update biases ----
    bias_output += np.sum(output_gradient, axis=0, keepdims=True) * training_factor
    bias_hidden += np.sum(hidden_gradient, axis=0, keepdims=True) * training_factor


In [109]:
print("\nInputs (normalized):")
print(inputs)

print("\nActual Marks:")
print(targets * 100)

print("\nPredicted Marks:")
print(predicted_output * 100)


Inputs (normalized):
[[0.2        0.33333333]
 [0.6        0.66666667]
 [1.         1.        ]]

Actual Marks:
[[7.]
 [8.]
 [9.]]

Predicted Marks:
[[8.859008  ]
 [7.82291865]
 [7.17051736]]
