In [80]:
import numpy as np

In [81]:
inputs=np.array([
 [1,2],
 [3,4],
 [5,6]
],dtype=float)
targets=np.array([
    [7],
    [8],
    [9]
],dtype=float)

In [82]:
## normalize data
inputs = inputs / np.max(inputs, axis=0)
targets = targets / 100.0

In [83]:
print(inputs)
print(targets)

[[0.2        0.33333333]
 [0.6        0.66666667]
 [1.         1.        ]]
[[0.07]
 [0.08]
 [0.09]]


In [84]:
def activate(x):## sigmoid
    return 1/(1+np.exp(-x))
def activate_derivative(x):
    return x*(1-x)

In [62]:
## example for transpose
print(input.T)

[[1. 3. 5.]
 [2. 4. 6.]]


In [78]:
num_input_features = inputs.shape[1]   # 2
num_hidden_neurons = 3
num_outputs = targets.shape[1]  

In [21]:
epoch=1000
training_factor=0.2 ## eta

In [55]:
## input to hidden
weights_input_to_hidden = np.random.uniform(size=(num_input_features, num_hidden_neurons))
bias_hidden = np.random.uniform(size=(1, num_hidden_neurons))

In [56]:
print(weights_input_to_hidden)
print(bias_hidden)

[[0.36812749 0.2700826  0.27476663]
 [0.89201574 0.34724169 0.52871744]
 [0.24612261 0.78153062 0.54940882]]
[[0.31201952 0.96118001 0.9268288 ]]


In [57]:
weights_hidden_to_output=np.random.uniform(size=(num_hidden_neurons,num_outputs))
bias_output=np.random.uniform(size=(1,num_outputs))

In [58]:
print(weights_hidden_to_output)
print(bias_output)

[[0.1910266 ]
 [0.91822115]
 [0.36817216]]
[[0.70109165]]


In [79]:
for _ in range(epoch):
     # ---- Forward pass ----
    hidden_input = np.dot(inputs, weights_input_to_hidden) + bias_hidden
    hidden_output = activate(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_to_output) + bias_output
    predicted_output = activate(final_input)

    # ---- Calculate error ----
    output_error = targets - predicted_output

    # ---- Backpropagation ----
    output_gradient = output_error * activate_derivative(predicted_output)

    hidden_error = np.dot(output_gradient, weights_hidden_to_output.T)
    hidden_gradient = hidden_error * activate_derivative(hidden_output)

    # ---- Update weights ----
    weights_hidden_to_output += np.dot(hidden_output.T, output_gradient) * learning_rate
    weights_input_to_hidden += np.dot(inputs.T, hidden_gradient) * learning_rate

    # ---- Update biases ----
    bias_output += np.sum(output_gradient, axis=0, keepdims=True) * learning_rate
    bias_hidden += np.sum(hidden_gradient, axis=0, keepdims=True) * learning_rate


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [76]:
print("\nInputs (normalized):")
print(inputs)

print("\nActual Marks:")
print(targets * 100)

print("\nPredicted Marks:")
print(predicted_output * 100)


Inputs (normalized):
[[0.2        0.33333333]
 [0.6        0.66666667]
 [1.         1.        ]]

Actual Marks:
[[0.0007]
 [0.0008]
 [0.0009]]

Predicted Marks:


NameError: name 'predicted_output' is not defined